### ISSUE TITLE
Farbliche Markierung des Anmeldestatus eines Spielers

### ISSUE THREAD

**Issue by TerranUlm** [opt-natter/MyBB-Plugin-OPT-MRS#1]
Der Text hinter jedem Spieler (Angemeldet, abgemeldet etc.) sollte farblich hervorgehoben werden. Abgemeldet / Angemeldet liest sich schon sehr ähnlich.

Realisiert werden sollte das natürlich über ein Plugin-sepezifisches Stylesheet, zum Start könnte die Farbdefinition ungefähr so aussehen:

rot = Abgemeldet
grün = Angemeldet
gelb = Unsicher
grau = keine Rückmeldung

**Comment by opt-natter** [comment]
umgesetzt.
https://github.com/opt-natter/MyBB-Plugin-OPT-MRS/commit/8f695c25e56689ce142df7de9cf33fc7f37dd373

**Comment by TerranUlm** [comment]
wie soll die Konfiguration funktionieren? Standardmäßig ist alles schwarz.

**Comment by TerranUlm** [comment]
Funktioniert!
