### ISSUE TITLE
Darstellung der Spieler ohne Rückmeldung

### ISSUE THREAD

**Issue by TerranUlm** [opt-natter/MyBB-Plugin-OPT-MRS#2]
Spieler, die noch keine Rückmeldung gegeben haben, sollten zusammen dargestellt werden, eventuell könnte man das auch aufklappbar machen, so wie man einzelne Forensektionen wegklappen kann.

**Comment by opt-natter** [comment]
erst Version umgesetzt. Test&Optimierungsbedarf
https://github.com/opt-natter/MyBB-Plugin-OPT-MRS/commit/8f695c25e56689ce142df7de9cf33fc7f37dd373

**Comment by TerranUlm** [comment]
wie soll das funktionieren? Ich finde keine Einstellung, Option o.ä.

**Comment by TerranUlm** [comment]
Funktioniert leider nicht wie erwartet, die Liste ist leer, obwohl es Benutzer ohne Rückmeldung gibt.

**Comment by opt-natter** [comment]
Hast du die Liste auch aufgeklappt? Es ist nur für möglich die Spieler ohne Rückmeldung der eigenen Armee zu sehen .Es muss die Berechtigung die komplette Armee oder die Summary zu sehen vorhanden sein.

**Comment by TerranUlm** [comment]
Mir wäre es lieber, das Ausklappen würde wie im Forum funktionieren, dort kann man die einzelnen Teilforen jeweils oben rechts ein- und ausblenden.

**Comment by TerranUlm** [comment]
Ist es eigentlich Absicht, dass sich alle Tabellen einklappen lassen?

**Comment by TerranUlm** [comment]
So kommt beim Chrome das korrekte Format raus, ohne das beim ein- und ausklappen die Spalten sich ändern:

``` HTML
<table border="0" cellspacing="1" cellpadding="4" class="tborder">
  <colgroup>
    <col style="width: 40%;">
    <col style="width: 40%;">
    <col style="width: 18%;">
    <col style="width: 2%;">
  </colgroup>
  <thead>
    <tr>
      <td class="thead" colspan="2"><strong>Gruppe: ↓↑ Keine Rückmeldung von folgenden Gruppenmitgliedern ↓↑:</strong></td>
      <td class="thead" colspan="2"><strong>0 Angemeldet</strong></td>
    </tr>
  </thead>
  <tbody style="display: table-row-group;">
    <tr class="tcat">
      <td><strong>Mitglieder</strong></td>
      <td><strong>Rückmeldung</strong></td>
      <td><strong>Bemerkung</strong></td>
      <td></td>
    </tr>
    <!-- start: optmatchresponse_show_response_user -->
    <tr class="trow1">
      <td><a href="https://www.opt-community.de/TEST/Forum/user-4042.html"><span style="color:red;">[RUS]41.|PFC.R@pToR</span></a></td>
      <td class="optmatchresponse_resp_0">Keine Rückmeldung</td>
      <td></td>
      <td></td>
    </tr>
    <!-- end: optmatchresponse_show_response_user -->  
    <tr><td colspan="4"></td></tr>   
  </tbody>
</table>
```

Anstatt die Breite der Spalte in "jeder" Zeile anzugeben wird die Breite jeder Spalte einmal am Kopf der Tabelle definiert.

**Comment by opt-natter** [comment]
ja, es ist Absicht, dass sich alle Tabellen einklappen lassen. Ich hab an dem Abend auch noch die gleiche Lösung gefunden :)

```
<col width="40%">
<col width="30%">
<col width="30%">
<col width="00%">
```

Musste eine neue Globale Variable einführen um das mybb collapse system einfach umzusetzen. Nebeneffekt: Mybb speichert die einklappten Tabellen.
